
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
public class Design extends javax.swing.JFrame {

    /**
     *
     */
    DefaultTableModel model;
    public Design() {
        initComponents();
        model=(DefaultTableModel)tbl.getModel();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gant1 = new gant();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfprocess = new javax.swing.JTextField();
        tfarrival = new javax.swing.JTextField();
        tfburst = new javax.swing.JTextField();
        tfpriority = new javax.swing.JTextField();
        badd = new javax.swing.JButton();
        bdelete = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        bcompute = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        opt = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        wtresult = new javax.swing.JLabel();
        tatresult = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CPU SCHEDULING SYSTEM");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Process");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(26, 38, 62, 20);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Arrival");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(26, 92, 62, 20);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Burst");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(26, 150, 62, 20);

        tfprocess.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfprocess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfprocessActionPerformed(evt);
            }
        });
        getContentPane().add(tfprocess);
        tfprocess.setBounds(117, 35, 70, 23);

        tfarrival.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfarrival.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfarrivalActionPerformed(evt);
            }
        });
        getContentPane().add(tfarrival);
        tfarrival.setBounds(117, 89, 70, 23);

        tfburst.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(tfburst);
        tfburst.setBounds(117, 145, 70, 23);

        tfpriority.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(tfpriority);
        tfpriority.setBounds(117, 195, 70, 23);

        badd.setBackground(new java.awt.Color(255, 255, 255));
        badd.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        badd.setForeground(new java.awt.Color(51, 51, 51));
        badd.setText("Add");
        badd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baddActionPerformed(evt);
            }
        });
        getContentPane().add(badd);
        badd.setBounds(14, 280, 80, 27);

        bdelete.setBackground(new java.awt.Color(255, 255, 255));
        bdelete.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        bdelete.setForeground(new java.awt.Color(51, 51, 51));
        bdelete.setText("Delete");
        bdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeleteActionPerformed(evt);
            }
        });
        getContentPane().add(bdelete);
        bdelete.setBounds(120, 280, 90, 27);

        bedit.setBackground(new java.awt.Color(255, 255, 255));
        bedit.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        bedit.setForeground(new java.awt.Color(51, 51, 51));
        bedit.setText("Edit");
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });
        getContentPane().add(bedit);
        bedit.setBounds(14, 340, 80, 27);

        bcompute.setBackground(new java.awt.Color(255, 255, 255));
        bcompute.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        bcompute.setForeground(new java.awt.Color(51, 51, 51));
        bcompute.setText("Compute");
        bcompute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcomputeActionPerformed(evt);
            }
        });
        getContentPane().add(bcompute);
        bcompute.setBounds(120, 340, 90, 27);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Select a Process");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(45, 413, 110, 30);

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Priority");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(26, 200, 62, 20);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Process", "Arrival", "Burst", "Priority", "WTT", "TAT"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(260, 9, 717, 255);

        opt.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        opt.setForeground(new java.awt.Color(51, 51, 51));
        opt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FCFS", "SJF", "RR", "Priority" }));
        getContentPane().add(opt);
        opt.setBounds(60, 460, 70, 24);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Average Waiting Time:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(320, 290, 150, 23);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Average Turnaround Time:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(320, 340, 170, 23);

        wtresult.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        wtresult.setForeground(new java.awt.Color(255, 255, 255));
        wtresult.setText("NULL");
        getContentPane().add(wtresult);
        wtresult.setBounds(520, 290, 65, 23);

        tatresult.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        tatresult.setForeground(new java.awt.Color(255, 255, 255));
        tatresult.setText("NULL");
        getContentPane().add(tatresult);
        tatresult.setBounds(520, 340, 65, 23);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Gant Chart");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(540, 390, 120, 20);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backc.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 980, 540);
        getContentPane().add(scroll);
        scroll.setBounds(213, 421, 764, 117);
        scroll.setViewportView(gant1.chartPanel);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 200, 60, 30);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Priority");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 200, 60, 30);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Burst");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(26, 151, 62, 20);

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Priority");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 210, 44, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(60, 460, 58, 20);

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(910, 10, 60, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfprocessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfprocessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfprocessActionPerformed

    private void baddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baddActionPerformed
        // TODO add your handling code here:
         model.insertRow(model.getRowCount(),new Object[]{tfprocess.getText(),tfarrival.getText(),tfburst.getText(),tfpriority.getText()});
    }//GEN-LAST:event_baddActionPerformed

    private void bdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeleteActionPerformed
        // TODO add your handling code here:
        model.removeRow(tbl.getSelectedRow());
    }//GEN-LAST:event_bdeleteActionPerformed

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
        // TODO add your handling code here:
        model.setValueAt(tfprocess.getText(), tbl.getSelectedRow(),0);
        model.setValueAt(tfarrival.getText(), tbl.getSelectedRow(),1);
        model.setValueAt(tfburst.getText(), tbl.getSelectedRow(),2);
        model.setValueAt(tfpriority.getText(), tbl.getSelectedRow(),3);
       
    }//GEN-LAST:event_beditActionPerformed

    private void bcomputeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcomputeActionPerformed
        // TODO add your handling code here:
                            String selected = (String) opt.getSelectedItem();
                
                CPUScheduler scheduler;
                
                switch (selected) {
                    case "FCFS":
                        scheduler = new FirstComeFirstServe();
                        break;
                    case "SJF":
                        scheduler = new ShortestJobFirst();
                        break;
                    case "Priority":
                        scheduler = new Priority();
                        break;
                    case "RR":
                        String tq = JOptionPane.showInputDialog("Time Quantum");
                        if (tq == null) {
                            return;
                        }
                        scheduler = new RoundRobin();
                        scheduler.setTimeQuantum(Integer.parseInt(tq)); 
                        break;
                    default:
                        return;
                }
                
                // model me jitne row the unte tak me loop chala raha hun.
                // ab unke columns ko row by row (one by one )scheduler me add kar raha hun.
                for (int i = 0; i < model.getRowCount(); i++)
                {
                    String process = (String) model.getValueAt(i, 0);
                    int at = Integer.parseInt((String) model.getValueAt(i, 1));
                    int bt = Integer.parseInt((String) model.getValueAt(i, 2));
                    int priority = Integer.parseInt((String) model.getValueAt(i, 3));
                   
                    // this one is for row setting in scheduler.
                    scheduler.add(new Row(process, at, bt,priority));
                }
                
                // ab process agae hai schduler me.
                // ab hame chalana hai desired algo.
                scheduler.process();
                
                // ab algo chal gaya hai.
                
                
                for (int i = 0; i < model.getRowCount(); i++)
                {
                    String process = (String) model.getValueAt(i, 0);
                    Row row = scheduler.getRow(process);
                    model.setValueAt(row.getWaitingTime(), i, 4);
                    model.setValueAt(row.getTurnaroundTime(), i, 5);
                }
                
                // printing the answer into two labels
                wtresult.setText(Double.toString(scheduler.getAverageWaitingTime()));
                tatresult.setText(Double.toString(scheduler.getAverageTurnAroundTime()));
                
                gant1.chartPanel.setTimeline(scheduler.getTimeline());
    }//GEN-LAST:event_bcomputeActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
        tfprocess.setText(String.valueOf(model.getValueAt(tbl.getSelectedRow(), 0)));
        tfarrival.setText(String.valueOf(model.getValueAt(tbl.getSelectedRow(), 1)));
        tfburst.setText(String.valueOf(model.getValueAt(tbl.getSelectedRow(), 2)));
        tfpriority.setText(String.valueOf(model.getValueAt(tbl.getSelectedRow(),3)));
      
    }//GEN-LAST:event_tblMouseClicked

    private void tfarrivalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfarrivalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfarrivalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Design().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton badd;
    private javax.swing.JButton bcompute;
    private javax.swing.JButton bdelete;
    private javax.swing.JButton bedit;
    private gant gant1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> opt;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JLabel tatresult;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField tfarrival;
    private javax.swing.JTextField tfburst;
    private javax.swing.JTextField tfpriority;
    private javax.swing.JTextField tfprocess;
    private javax.swing.JLabel wtresult;
    // End of variables declaration//GEN-END:variables
}
